### ISSUE TITLE
Boards are falling off MQTT updating after a few hours

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#105]

**Comment by rjmcdougall** [comment]
in sendUpdate(), not protected by try/catch:

        if (mqttClient.isConnected() == false && haveConnected) {
            Log.d(TAG, mqttClient.getBufferedMessageCount() + " messages in buffer");
        }

in doConnect() , not protected by try/catch:

                        // We get failed reconnects because JWT key expires in Google IoT
                        // Force a disconnect then reconnect
                        android.net.wifi.SupplicantState s = mWiFiManager.getConnectionInfo().getSupplicantState();
                        NetworkInfo.DetailedState state = WifiInfo.getDetailedStateOf(s);

in doConnect() , try/catch not protecting anything useful:

                        if (state == NetworkInfo.DetailedState.CONNECTED) {
                            if (mqttClient.isConnected() == false) {
                                try {
                                    Log.d(TAG, "MQTT disconnected but Wifi connected, forcing disconnect");
                                    haveConnected = false;
                                } catch (Exception e) {
                                }
                            }
                        }

in doConnect() , not sure why this was originally needed and it's again needed:


                        // Sent fake wake-up event to android MQTT Client
                        /*
                        try {
                            Intent in = new Intent(ConnectivityManager.CONNECTIVITY_ACTION);
                            LocalBroadcastManager.getInstance(mContext).sendBroadcast(in);
                        } catch (Exception e) {
                            Log.d(TAG, "could not send CONNECTIVITY_ACTION");
                        }
                        */

**Comment by rjmcdougall** [comment]
On the server side: 
mqtt: SERVER: The connection was closed because there is another active connection with the same device ID.

Possibly because bbinstaller and bb share the same mqtt device.

**Comment by rjmcdougall** [comment]
More on akula:

Heartbeat (MQTT only)	
Jun 25, 2018, 6:09:51 AM Telemetry event received	
Jun 26, 2018, 1:30:31 PM Device state event received	
—
Config sent	Jun 25, 2018, 6:07:51 AM
Config ACK (MQTT only)	
—
Error Jun 26, 2018, 1:17:08 PM: mqtt: SERVER: The authorization token expired.

**Comment by rjmcdougall** [comment]
Akula is still sending GPS through IOT, but no battery telemetry.

**Comment by rjmcdougall** [comment]
Found the smoking gun:

"BB Battery Monitor" prio=5 tid=18 Native
  | group="main" sCount=1 dsCount=0 obj=0x12dcc4c0 self=0x559c52a740
  | sysTid=2062 nice=0 cgrp=default sched=0/0 handle=0x7f984ac450
  | state=S schedstat=( 2932115752 918129302 5893 ) utm=208 stm=85 core=0 HZ=100
  | stack=0x7f983aa000-0x7f983ac000 stackSize=1037KB
  | held mutexes=
  kernel: __switch_to+0x70/0x7c
  kernel: reap_as+0x94/0xd8
  kernel: usbdev_do_ioctl+0x368/0x1038
  kernel: usbdev_ioctl+0x8/0x18
  kernel: do_vfs_ioctl+0x4c4/0x598
  kernel: SyS_ioctl+0x5c/0x88
  kernel: cpu_switch_to+0x48/0x4c
  native: #00 pc 000000000006ac94  /system/lib64/libc.so (__ioctl+8)
  native: #01 pc 0000000000074cb4  /system/lib64/libc.so (ioctl+100)
  native: #02 pc 00000000000028f0  /system/lib64/libusbhost.so (usb_request_wait+40)
  native: #03 pc 0000000000123adc  /system/lib64/libandroid_runtime.so (???)
  native: #04 pc 000000000000013c  /data/dalvik-cache/arm64/system@framework@boot.oat (Java_android_hardware_usb_UsbDeviceConnection_native_1request_1wait__+128)
  at android.hardware.usb.UsbDeviceConnection.native_request_wait(Native method)
  at android.hardware.usb.UsbDeviceConnection.requestWait(UsbDeviceConnection.java:228)
  at com.hoho.android.usbserial.driver.CdcAcmSerialDriver$CdcAcmSerialPort.write(CdcAcmSerialDriver.java:247)
  at com.richardmcdougall.bb.CmdMessenger.flushWrites(CmdMessenger.java:118)
  at com.richardmcdougall.bb.BurnerBoard.flush2Board(BurnerBoard.java:528)
  at com.richardmcdougall.bb.BurnerBoardAzul.showBattery(BurnerBoardAzul.java:504)
  at com.richardmcdougall.bb.BBService.batteryThread(BBService.java:1441)
  at com.richardmcdougall.bb.BBService.access$000(BBService.java:57)
  at com.richardmcdougall.bb.BBService$4.run(BBService.java:317)
  at java.lang.Thread.run(Thread.java:818)
