### ISSUE TITLE
'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object 

### ISSUE THREAD

**Issue by danielkeithw** [rjmcdougall/BB#117]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.richardmcdougall.bb, PID: 3478
                  java.lang.RuntimeException: Unable to create service com.richardmcdougall.bb.BBService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
                      at android.app.ActivityThread.access$1900(ActivityThread.java:150)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
                      at com.richardmcdougall.bb.BBService.onCreate(BBService.java:202)
                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
                      at android.app.ActivityThread.access$1900(ActivityThread.java:150) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by danielkeithw** [comment]
had to move this:

        mContext = getApplicationContext();

up to the top of the onCreate method
